services:
  postgres-db:
    image: postgres:15-alpine
    container_name: customer_support_db
    environment:
      POSTGRES_DB: customer_support
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d customer_support"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: customer_support_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpassword
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-service:
    build: .
    container_name: customer_support_app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/customer_support
      DB_USER: pguser
      DB_PASSWORD: pgpassword
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: rabbituser
      SPRING_RABBITMQ_PASSWORD: rabbitpassword
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  pgdata: